/**
 * UI copy layer (BASELINE-BUILD §3.4 / readme CONTENT FUNDAMENTALS).
 * nb-NO is the default locale; English is available for bilingual-ready merchants.
 * Components must call `t()` — do not hardcode UI strings.
 */
import {merchantConfig} from '~/merchant.config';

export type LocaleCode = 'nb-NO' | 'en';

type Messages = Record<string, string>;

const nb: Messages = {
  // Nav / crumbs
  'nav.home': 'Hjem',
  'nav.catalog': 'Katalog',
  'nav.categories': 'Kategorier',
  'nav.account': 'Konto',
  'nav.help': 'Hjelp',
  'nav.quotes': 'Tilbud',
  'nav.myPages': 'Mine sider',
  'nav.login': 'Logg inn',
  'nav.cart': 'Handlekurv',
  'nav.quickOrder': 'Hurtigbestilling',
  'nav.customerService': 'Kundeservice',
  'nav.shippingReturns': 'Frakt & retur',
  'nav.contact': 'Kontakt',
  'nav.orderHistory': 'Ordrehistorikk',
  'nav.submenu': 'Undermeny',
  'nav.openSubmenu': 'Vis undermeny for {title}',
  'nav.closeSubmenu': 'Skjul undermeny for {title}',

  // Chrome
  'chrome.topBar': 'Engros for proff · Levering i hele Norge',
  'chrome.localeCurrency': 'nb-NO · NOK',
  'chrome.searchPlaceholder': 'Søk SKU, produkt eller kategori',
  'chrome.footerBlurb':
    'Demonstrasjonsbutikk bygget på den headless B2B-malen. Innhold er fiktivt.',
  'chrome.footerLegal': 'Org. 912 345 678 · Vilkår · Personvern',
  'chrome.footerCopyright': '© {year} {merchant} AS — demo',

  // Pagination
  'pagination.loading': 'Laster…',
  'pagination.loadPrevious': 'Last forrige',
  'pagination.loadMore': 'Last flere',

  // PLP
  'plp.filters': 'Filtre',
  'plp.filter': 'Filtrer',
  'plp.closeFilters': 'Lukk filtre',
  'plp.close': 'Lukk',
  'plp.showResults': 'Vis resultater',
  'plp.productCount': '{count} produkter',
  'plp.productCountLowerBound': '{count}+ produkter',
  'plp.filtered': ' · filtrert',
  'plp.activeFilters': 'Aktive filtre',
  'plp.clearAll': 'Fjern alle',
  'plp.clearAllFilters': 'Fjern alle filtre',
  'plp.emptyTitle': 'Ingen produkter',
  'plp.emptyFiltered':
    'Ingen produkter matcher de valgte filtrene. Prøv å fjerne noen filtre.',
  'plp.emptyCollection': 'Det er ingen produkter i denne samlingen ennå.',
  'plp.priceTo': 'til',
  'plp.priceFrom': 'Fra {value}',
  'plp.priceUntil': 'Til {value}',
  'plp.price': 'Pris',
  'plp.priceMinAria': '{label} minimum',
  'plp.priceMaxAria': '{label} maksimum',
  'plp.catalogFallbackTitle': 'Katalog',
  'plp.productsAria': 'Produkter',

  // Collections index
  'collections.title': 'Kategorier',
  'collections.metaDescription':
    'Utforsk produktkategorier og samlinger i katalogen.',
  'collections.subtitle': 'Utforsk samlinger i katalogen',
  'collections.emptyTitle': 'Ingen samlinger',
  'collections.emptyBody':
    'Det er ingen samlinger publisert i butikken ennå.',
  'collections.aria': 'Kategorier',

  // Sort
  'sort.relevance': 'Relevans',
  'sort.title-asc': 'Navn A–Å',
  'sort.title-desc': 'Navn Å–A',
  'sort.price-asc': 'Pris lav–høy',
  'sort.price-desc': 'Pris høy–lav',

  // Commerce / DS
  'price.loginForPrice': 'Logg inn for pris',
  'price.exVat': 'eks. mva',
  'price.incVat': 'inkl. mva',
  'price.yourPriceSave': '−{pct}% din pris',
  'stock.in': 'På lager',
  'stock.low': 'Få igjen',
  'stock.lowWithQty': 'Få igjen ({qty})',
  'stock.out': 'Utsolgt',
  'stock.backorder': 'Restordre',
  'product.addToCart': 'Legg i kurv',
  'product.addToCartLong': 'Legg i handlekurv',
  'product.requestQuote': 'Be om tilbud',
  'cart.title': 'Handlekurv',
  'cart.close': 'Lukk handlekurv',
  'cart.empty': 'Handlekurven er tom',
  'cart.checkout': 'Gå til kasse',
  'cart.continue': 'Fortsett å handle',
  'cart.viewCart': 'Vis kurv',
  'cart.addedToast': 'Lagt i handlekurv',
  'cart.addedToastMany': '{count} varer lagt i handlekurv',
  'cart.lineQty': '{qty} stk',
  'cart.remove': 'Fjern',
  'cart.taxNote': 'MVA og frakt beregnes i kassen',
  'cart.checkoutWithTotal': 'Gå til kasse · {total}',
  'quickAdd.title': 'Legg i kurv',
  'quickAdd.close': 'Lukk',
  'quickAdd.loading': 'Laster produkt…',
  'quickAdd.viewDetails': 'Se full produktside',
  'qty.breaksHeading': 'Mengderabatt',
  'qty.count': 'Antall',
  'qty.pricePer': 'Pris pr. {unit}',
  'qty.unit': 'stk',

  // PDP
  'pdp.noImage': 'Ingen produktbilde',
  'pdp.sku': 'SKU {sku}',
  'pdp.handle': 'Handle {handle}',
  'pdp.description': 'Beskrivelse',
  'pdp.vendor': 'Leverandør',
  'pdp.productType': 'Produkttype',
  'pdp.variant': 'Variant',
  'pdp.stockStatus': 'Lagerstatus',
  'pdp.priceList': 'Prisliste',
  'pdp.vat': 'MVA',
  'pdp.gateHint': 'Logg inn med bedriftskontoen for pris og bestilling.',
  'pdp.notFound': 'Ikke funnet',
  'pdp.metaFallback': 'Produkt',
  'pdp.showImage': 'Vis bilde {n}',

  // Home (UI chrome — campaign copy lives in Admin metaobjects)
  'home.metaTitle': 'Engros VVS & industri',
  'home.categories': 'Kategorier',
  'home.seeAll': 'Se alle',
  'home.featured': 'Utvalgte produkter',
  'home.fullCatalog': 'Se alle',
  'home.itemCount': '{count} varer',
  'home.hero.eyebrow': 'Engros · VVS & industri',
  'home.hero.title': 'Deler på lager.\nPriser for din bedrift.',
  'home.hero.body':
    'Bestill ventiler, koblinger og rørdeler til avtalte priser. Logg inn for å se din prisliste, lagerstatus i sanntid og bestille på nytt fra tidligere ordre.',
  'home.hero.ctaPrimary': 'Se katalogen',
  'home.hero.ctaSecondary': 'Be om konto',
  'home.hero.ctaSecondaryLoggedIn': 'Mine sider',
  'home.account.title': 'Din konto',
  'home.account.priceList': 'Prisliste',
  'home.account.terms': 'Betalingsvilkår',
  'home.account.openOrders': 'Åpne ordrer',
  'home.account.creditAvailable': 'Kreditt tilgjengelig',
  'home.account.goToAccount': 'Gå til Mine sider',
  'home.account.guestHint':
    'Logg inn for å se priser, lager og ordrehistorikk for din bedrift.',
  'home.account.login': 'Logg inn',

  // Login
  'login.metaTitle': 'Logg inn — Nordvik Industri',
  'login.title': 'Logg inn',
  'login.bodyDemo':
    'Bedriftspålogging går via Shopify Customer Account API. I denne demoen logger du inn som Marius Hansen hos Bergen Rør & VVS AS.',
  'login.bodyReal':
    'Logg inn med din bedriftskonto via Shopify. Du blir sendt til Shopify for sikker pålogging, deretter tilbake til Mine sider.',
  'login.ctaDemo': 'Logg inn som demo-bruker',
  'login.ctaReal': 'Fortsett til Shopify-pålogging',
  'login.footnote':
    'Identitet, sesjon og passord eies av Shopify (Customer Account API). Vi bygger kun kontogrensesnittet.',
  'login.b2bRequired.title': 'Bedriftskonto kreves',
  'login.b2bRequired.body':
    'Du er innlogget via Shopify, men denne kontoen er ikke klar for B2B (Mine sider).',
  'login.b2bRequired.bodyWithEmail':
    'Du er innlogget som {email}, men denne kontoen er ikke klar for B2B (Mine sider).',
  'login.b2bRequired.checklist':
    'Sjekk i Shopify Admin: kundetag «b2b», metafeltet sparklayer.authentication, og sparklayer.price_lists — alle med tilgang for Customer Account API.',
  'login.b2bRequired.logout': 'Logg ut og prøv en annen konto',

  // Search
  'search.noResults': 'Ingen treff. Prøv et annet søk.',
  'search.title': 'Søk',
  'search.metaTitle': 'Søk',
  'search.metaTitleWithTerm': 'Søk: {term}',
  'search.prompt': 'Skriv inn et søkeord for å finne produkter, sider og artikler.',
  'search.resultsTitle': 'Treff for «{term}»',
  'search.productsAria': 'Søketreff',
  'search.pages': 'Sider',
  'search.articles': 'Artikler',
  'search.predictiveAria': 'Forslag mens du søker',
  'search.predictiveLoading': 'Søker…',
  'search.viewAll': 'Se alle treff for «{term}»',
  'search.collections': 'Samlinger',
  'search.products': 'Produkter',
  'search.queries': 'Forslag',
  'search.noResultsFor': 'Ingen treff for «{term}»',

  // Blogs / policies / content chrome
  'blogs.title': 'Blogg',
  'blogs.metaTitle': 'Blogg',
  'policies.title': 'Retningslinjer',
  'policies.metaTitle': 'Retningslinjer',
  'policies.back': 'Tilbake til retningslinjer',
  'policies.notFound': 'Fant ikke retningslinjen',
  'policies.none': 'Ingen retningslinjer funnet',
  'content.notFound': 'Ikke funnet',

  // Errors
  'error.oops': 'Noe gikk galt',
  'error.unknown': 'Ukjent feil',
  'error.notFound': 'Siden ble ikke funnet',
  'error.linkExpired': 'Lenken kan være utløpt. Prøv på nytt fra butikken.',

  // Aside / scaffold chrome
  'aside.close': 'Lukk',
  'chrome.menu': 'Meny',
  'chrome.closeMenu': 'Lukk meny',
  'chrome.loadingCart': 'Laster handlekurv…',
  'chrome.loading': 'Laster…',
  'chrome.fallbackBlog': 'Blogg',
  'chrome.fallbackPolicies': 'Retningslinjer',
  'chrome.fallbackAbout': 'Om oss',
  'chrome.fallbackPrivacy': 'Personvern',
  'chrome.fallbackRefund': 'Returrett',
  'chrome.fallbackShipping': 'Frakt',
  'chrome.fallbackTerms': 'Vilkår',

  // Cart page / Hydrogen cart scaffold
  'cart.metaTitle': 'Handlekurv',
  'cart.pageAria': 'Handlekurv',
  'cart.drawerAria': 'Handlekurv-skuff',
  'cart.lineItems': 'Varer',
  'cart.emptyPrompt': 'Ser ut som du ikke har lagt noe i handlekurven ennå.',
  'cart.totals': 'Totaler',
  'cart.subtotal': 'Delsum',
  'cart.discounts': 'Rabatter',
  'cart.removeDiscount': 'Fjern rabatt',
  'cart.discountCode': 'Rabattkode',
  'cart.applyDiscount': 'Bruk rabattkode',
  'cart.apply': 'Bruk',
  'cart.giftCards': 'Gavekort',
  'cart.appliedGiftCards': 'Brukte gavekort',
  'cart.giftCardCode': 'Gavekortkode',
  'cart.applyGiftCard': 'Bruk gavekort',
  'cart.quantity': 'Antall',
  'cart.qtyDecrease': 'Reduser antall',
  'cart.qtyIncrease': 'Øk antall',
  'cart.continueCheckout': 'Fortsett til kassen',
  'cart.lineItemWith': 'Vare med {title}',

  // Qty stepper a11y
  'qty.decrease': 'Reduser',
  'qty.increase': 'Øk',
  'tag.remove': 'Fjern',

  // Demo marker (readme: literal DEMO DATA)
  'demo.badge': 'DEMO DATA',
  'demo.badgeTitle': 'Mock-data fra integrasjonssøm',

  // Order status (readme status language)
  'orderStatus.draft': 'Utkast',
  'orderStatus.quote': 'Tilbud',
  'orderStatus.pending': 'Avventer',
  'orderStatus.confirmed': 'Bekreftet',
  'orderStatus.processing': 'Behandles',
  'orderStatus.shipped': 'På vei',
  'orderStatus.delivered': 'Levert',
  'orderStatus.invoiced': 'Fakturert',
  'orderStatus.paid': 'Betalt',
  'orderStatus.overdue': 'Forfalt',
  'orderStatus.cancelled': 'Kansellert',
  'orderStatus.returned': 'Returnert',

  // Account chrome
  'account.sidebarTitle': 'Mine sider',
  'account.toStore': 'Til butikken',
  'account.logout': 'Logg ut',
  'account.orgMeta': 'Org. {orgnr} · {priceList}',
  'account.nav.ordering': 'Bestilling',
  'account.nav.overview': 'Oversikt',
  'account.nav.quickOrder': 'Hurtigbestilling',
  'account.nav.lists': 'Mine lister',
  'account.nav.ordersQuotes': 'Ordrer & tilbud',
  'account.nav.orders': 'Ordrer',
  'account.nav.quotes': 'Tilbud',
  'account.nav.company': 'Bedrift',
  'account.nav.priceList': 'Prisliste',
  'account.nav.credit': 'Kreditt',
  'account.nav.users': 'Brukere',
  'account.nav.notifications': 'Varslinger',
  'account.meta.suffix': 'Mine sider',
  'account.notFound': 'Ikke funnet',

  // Account dashboard
  'account.dash.greeting': 'God morgen, {name}',
  'account.dash.welcome': 'Velkommen tilbake',
  'account.dash.newOrder': 'Ny bestilling',
  'account.dash.recentOrders': 'Siste ordrer',
  'account.dash.allOrders': 'Alle ordrer',
  'account.dash.openOrders': 'Åpne ordrer',
  'account.dash.credit': 'Kreditt',
  'account.dash.priceList': 'Prisliste',
  'account.dash.colOrder': 'Ordre',
  'account.dash.colDate': 'Dato',
  'account.dash.colStatus': 'Status',
  'account.dash.colTotal': 'Totalt',

  // Account shared table / actions
  'account.action.download': 'Last ned',
  'account.action.reorder': 'Bestill på nytt',
  'account.action.view': 'Vis',
  'account.action.track': 'Sporing',
  'account.action.save': 'Lagre',
  'account.action.create': 'Opprett',
  'account.action.delete': 'Slett',
  'account.action.update': 'Oppdater',
  'account.action.updating': 'Oppdaterer…',
  'account.empty.orders': 'Ingen ordrer ennå.',
  'account.empty.quotes': 'Ingen tilbud ennå.',
  'account.empty.lists': 'Ingen lister ennå.',
  'account.empty.addresses': 'Ingen adresser ennå.',

  // Account page titles
  'account.orders.title': 'Ordrer',
  'account.orders.meta': 'Ordrer — Mine sider',
  'account.quotes.title': 'Tilbud',
  'account.quotes.meta': 'Tilbud — Mine sider',
  'account.lists.title': 'Mine lister',
  'account.lists.meta': 'Lister — Mine sider',
  'account.quickOrder.title': 'Hurtigbestilling',
  'account.quickOrder.meta': 'Hurtigbestilling — Mine sider',
  'account.priceList.title': 'Prisliste',
  'account.priceList.meta': 'Prisliste — Mine sider',
  'account.credit.title': 'Kreditt',
  'account.credit.meta': 'Kreditt — Mine sider',
  'account.users.title': 'Brukere',
  'account.users.meta': 'Brukere — Mine sider',
  'account.notifications.title': 'Varslinger',
  'account.notifications.meta': 'Varslinger — Mine sider',
  'account.profile.title': 'Min profil',
  'account.profile.meta': 'Profil — Mine sider',
  'account.addresses.title': 'Adresser',
  'account.addresses.meta': 'Adresser — Mine sider',
  'account.overview.meta': 'Oversikt — Mine sider',

  // Profile / addresses (shared labels)
  'account.profile.firstName': 'Fornavn',
  'account.profile.lastName': 'Etternavn',
  'account.profile.email': 'E-post',
  'account.profile.phone': 'Telefon',
  'account.addresses.add': 'Ny adresse',
  'account.addresses.edit': 'Rediger adresse',
  'account.addresses.default': 'Sett som standardadresse',
  'account.addresses.company': 'Firma',
  'account.addresses.address1': 'Adresse',
  'account.addresses.address2': 'Adresse linje 2',
  'account.addresses.city': 'Sted',
  'account.addresses.zip': 'Postnummer',
  'account.addresses.province': 'Fylke',
  'account.addresses.country': 'Land',

  // Checkout
  'checkout.metaTitle': 'Kasse — {merchant}',
  'checkout.title': 'Kasse',
  'checkout.successTitle': 'Ordre mottatt',
  'checkout.successBody': 'Takk. Ordren er registrert.',
  'checkout.pay': 'Betal',
  'checkout.summary': 'Oppsummering',
  'checkout.empty': 'Handlekurven er tom.',
  'checkout.requestQuote': 'Send som forespørsel',

  // Account / checkout residual UI
  'account.users.subtitle':
    'Teammedlemmer, roller og bestillinger som venter på godkjenning',
  'account.users.invite': 'Inviter bruker',
  'account.users.reject': 'Avvis',
  'account.users.approve': 'Godkjenn',
  'account.users.members': 'Teammedlemmer',
  'account.users.role': 'Rolle',
  'account.users.orderLimit': 'Bestillingsgrense',
  'account.users.unlimited': 'Ubegrenset',
  'account.users.active': 'Aktiv',
  'account.users.invited': 'Invitert',
  'account.users.edit': 'Rediger',
  'account.quickOrder.subtitle':
    'Skriv eller lim inn SKU og antall — legg hele kurven til på én gang',
  'account.quickOrder.sku': 'SKU',
  'account.quickOrder.product': 'Produkt',
  'account.quickOrder.unknownSku': 'Ukjent SKU',
  'account.quickOrder.validLines': 'Gyldige linjer',
  'account.quickOrder.paste': 'Lim inn fra regneark',
  'account.quickOrder.pasteHint': 'SKU  antall',
  'account.credit.limit': 'Kredittgrense',
  'account.credit.used': 'Brukt',
  'account.credit.available': 'Ledig',
  'account.credit.invoices': 'Fakturaer',
  'account.credit.invoice': 'Faktura',
  'account.credit.due': 'Forfall',
  'account.notifications.subtitle':
    'Hendelser på kontoen og varer du følger',
  'account.notifications.markAll': 'Merk alle som lest',
  'account.notifications.recent': 'Nylig',
  'account.notifications.watchingStock': 'Følger lagerstatus',
  'account.notifications.unfollow': 'Slutt å følge',
  'account.lists.subtitle':
    'Lagrede handlelister og planlagte, gjentakende bestillinger',
  'account.lists.new': 'Ny liste',
  'account.lists.product': 'Produkt',
  'account.lists.sku': 'SKU',
  'account.lists.changePlan': 'Endre plan',
  'account.quotes.subtitle': 'Forespørsler og aktive tilbud',
  'account.quotes.validUntil': 'Gyldig til',
  'account.quotes.lineItems': 'Varelinjer',
  'account.quotes.listPrice': 'Listepris',
  'account.quotes.offerPrice': 'Tilbudspris',
  'account.quotes.youSave': 'Du sparer',
  'account.priceList.product': 'Produkt',
  'account.priceList.sku': 'SKU',
  'account.priceList.listPrice': 'Listepris',
  'account.priceList.yourPrice': 'Din pris',
  'account.priceList.discount': 'Rabatt',
  'account.orders.export': 'Eksporter',
  'account.orders.reference': 'Referanse',
  'account.orders.lineItems': 'Varelinjer',
  'account.orders.product': 'Produkt',
  'account.orders.sku': 'SKU',
  'account.orders.shipping': 'Frakt',
  'account.dash.mostOrdered': 'Bestilt oftest',
  'checkout.orderInfo': 'Bestillingsinfo',
  'checkout.poPlaceholder': 'f.eks. PO-2026-0345',
  'checkout.notePlaceholder': 'Valgfri melding til lager',
  'checkout.shippingAddress': 'Leveringsadresse',
  'checkout.default': 'Standard',
  'checkout.invoice': 'Faktura',
  'checkout.invoiceTerms': 'Netto 30 · din avtalte kredittgrense',
  'checkout.card': 'Kort',
  'checkout.cardHint': 'Betal nå med firmakort',
  'checkout.shipping': 'Frakt',
};

const en: Messages = {
  'nav.home': 'Home',
  'nav.catalog': 'Catalog',
  'nav.categories': 'Categories',
  'nav.account': 'Account',
  'nav.help': 'Help',
  'nav.quotes': 'Quotes',
  'nav.myPages': 'My account',
  'nav.login': 'Sign in',
  'nav.cart': 'Cart',
  'nav.quickOrder': 'Quick order',
  'nav.customerService': 'Customer service',
  'nav.shippingReturns': 'Shipping & returns',
  'nav.contact': 'Contact',
  'nav.orderHistory': 'Order history',
  'nav.submenu': 'Submenu',
  'nav.openSubmenu': 'Show submenu for {title}',
  'nav.closeSubmenu': 'Hide submenu for {title}',

  'chrome.topBar': 'Wholesale for professionals · Nationwide delivery',
  'chrome.localeCurrency': 'en · NOK',
  'chrome.searchPlaceholder': 'Search SKU, product or category',
  'chrome.footerBlurb':
    'Demo storefront built on the headless B2B template. Content is fictional.',
  'chrome.footerLegal': 'Org. 912 345 678 · Terms · Privacy',
  'chrome.footerCopyright': '© {year} {merchant} AS — demo',

  'pagination.loading': 'Loading…',
  'pagination.loadPrevious': 'Load previous',
  'pagination.loadMore': 'Load more',

  'plp.filters': 'Filters',
  'plp.filter': 'Filter',
  'plp.closeFilters': 'Close filters',
  'plp.close': 'Close',
  'plp.showResults': 'Show results',
  'plp.productCount': '{count} products',
  'plp.productCountLowerBound': '{count}+ products',
  'plp.filtered': ' · filtered',
  'plp.activeFilters': 'Active filters',
  'plp.clearAll': 'Clear all',
  'plp.clearAllFilters': 'Clear all filters',
  'plp.emptyTitle': 'No products',
  'plp.emptyFiltered':
    'No products match the selected filters. Try removing some filters.',
  'plp.emptyCollection': 'There are no products in this collection yet.',
  'plp.priceTo': 'to',
  'plp.priceFrom': 'From {value}',
  'plp.priceUntil': 'Up to {value}',
  'plp.price': 'Price',
  'plp.priceMinAria': '{label} minimum',
  'plp.priceMaxAria': '{label} maximum',
  'plp.catalogFallbackTitle': 'Catalog',
  'plp.productsAria': 'Products',

  'collections.title': 'Categories',
  'collections.metaDescription':
    'Browse product categories and collections in the catalog.',
  'collections.subtitle': 'Browse collections in the catalog',
  'collections.emptyTitle': 'No collections',
  'collections.emptyBody': 'No collections are published in the store yet.',
  'collections.aria': 'Categories',

  'sort.relevance': 'Relevance',
  'sort.title-asc': 'Name A–Z',
  'sort.title-desc': 'Name Z–A',
  'sort.price-asc': 'Price low–high',
  'sort.price-desc': 'Price high–low',

  'price.loginForPrice': 'Sign in for price',
  'price.exVat': 'ex. VAT',
  'price.incVat': 'inc. VAT',
  'price.yourPriceSave': '−{pct}% your price',
  'stock.in': 'In stock',
  'stock.low': 'Low stock',
  'stock.lowWithQty': 'Low stock ({qty})',
  'stock.out': 'Sold out',
  'stock.backorder': 'Backorder',
  'product.addToCart': 'Add to cart',
  'product.addToCartLong': 'Add to cart',
  'product.requestQuote': 'Request quote',
  'cart.title': 'Cart',
  'cart.close': 'Close cart',
  'cart.empty': 'Your cart is empty',
  'cart.checkout': 'Go to checkout',
  'cart.continue': 'Continue shopping',
  'cart.viewCart': 'View cart',
  'cart.addedToast': 'Added to cart',
  'cart.addedToastMany': '{count} items added to cart',
  'cart.lineQty': '{qty} pcs',
  'cart.remove': 'Remove',
  'cart.taxNote': 'Taxes and shipping calculated at checkout',
  'cart.checkoutWithTotal': 'Checkout · {total}',
  'quickAdd.title': 'Add to cart',
  'quickAdd.close': 'Close',
  'quickAdd.loading': 'Loading product…',
  'quickAdd.viewDetails': 'View full product page',
  'qty.breaksHeading': 'Volume pricing',
  'qty.count': 'Quantity',
  'qty.pricePer': 'Price per {unit}',
  'qty.unit': 'ea',

  'pdp.noImage': 'No product image',
  'pdp.sku': 'SKU {sku}',
  'pdp.handle': 'Handle {handle}',
  'pdp.description': 'Description',
  'pdp.vendor': 'Vendor',
  'pdp.productType': 'Product type',
  'pdp.variant': 'Variant',
  'pdp.stockStatus': 'Stock status',
  'pdp.priceList': 'Price list',
  'pdp.vat': 'VAT',
  'pdp.gateHint': 'Sign in with your company account for prices and ordering.',
  'pdp.notFound': 'Not found',
  'pdp.metaFallback': 'Product',
  'pdp.showImage': 'Show image {n}',

  'home.metaTitle': 'Wholesale plumbing & industrial',
  'home.categories': 'Categories',
  'home.seeAll': 'See all',
  'home.featured': 'Featured products',
  'home.fullCatalog': 'See all',
  'home.itemCount': '{count} items',
  'home.hero.eyebrow': 'Wholesale · Plumbing & industrial',
  'home.hero.title': 'Parts in stock.\nPrices for your business.',
  'home.hero.body':
    'Order valves, fittings and pipe parts at contracted prices. Sign in to see your price list, live stock and reorder from past orders.',
  'home.hero.ctaPrimary': 'Browse catalog',
  'home.hero.ctaSecondary': 'Request an account',
  'home.hero.ctaSecondaryLoggedIn': 'My account',
  'home.account.title': 'Your account',
  'home.account.priceList': 'Price list',
  'home.account.terms': 'Payment terms',
  'home.account.openOrders': 'Open orders',
  'home.account.creditAvailable': 'Available credit',
  'home.account.goToAccount': 'Go to My account',
  'home.account.guestHint':
    'Sign in to see prices, stock and order history for your company.',
  'home.account.login': 'Sign in',

  'login.metaTitle': 'Sign in — Nordvik Industri',
  'login.title': 'Sign in',
  'login.bodyDemo':
    'Business sign-in uses the Shopify Customer Account API. In this demo you sign in as Marius Hansen at Bergen Rør & VVS AS.',
  'login.bodyReal':
    'Sign in with your company account via Shopify. You will be redirected to Shopify for secure authentication, then back to My account.',
  'login.ctaDemo': 'Sign in as demo user',
  'login.ctaReal': 'Continue to Shopify sign-in',
  'login.footnote':
    'Identity, session and passwords are owned by Shopify (Customer Account API). We only build the account UI.',
  'login.b2bRequired.title': 'Business account required',
  'login.b2bRequired.body':
    'You are signed in with Shopify, but this account is not set up for B2B (My account).',
  'login.b2bRequired.bodyWithEmail':
    'You are signed in as {email}, but this account is not set up for B2B (My account).',
  'login.b2bRequired.checklist':
    'In Shopify Admin, confirm the customer has the «b2b» tag, sparklayer.authentication, and sparklayer.price_lists — with Customer Account API access enabled.',
  'login.b2bRequired.logout': 'Sign out and try another account',

  'search.noResults': 'No results, try a different search.',
  'search.title': 'Search',
  'search.metaTitle': 'Search',
  'search.metaTitleWithTerm': 'Search: {term}',
  'search.prompt': 'Enter a search term to find products, pages and articles.',
  'search.resultsTitle': 'Results for “{term}”',
  'search.productsAria': 'Search results',
  'search.pages': 'Pages',
  'search.articles': 'Articles',
  'search.predictiveAria': 'Search suggestions',
  'search.predictiveLoading': 'Searching…',
  'search.viewAll': 'View all results for “{term}”',
  'search.collections': 'Collections',
  'search.products': 'Products',
  'search.queries': 'Suggestions',
  'search.noResultsFor': 'No results found for “{term}”',

  'blogs.title': 'Blog',
  'blogs.metaTitle': 'Blog',
  'policies.title': 'Policies',
  'policies.metaTitle': 'Policies',
  'policies.back': 'Back to policies',
  'policies.notFound': 'Could not find the policy',
  'policies.none': 'No policies found',
  'content.notFound': 'Not found',

  'error.oops': 'Something went wrong',
  'error.unknown': 'Unknown error',
  'error.notFound': 'Page not found',
  'error.linkExpired': 'This link may be expired. Try again from the store.',

  'aside.close': 'Close',
  'chrome.menu': 'Menu',
  'chrome.closeMenu': 'Close menu',
  'chrome.loadingCart': 'Loading cart…',
  'chrome.loading': 'Loading…',
  'chrome.fallbackBlog': 'Blog',
  'chrome.fallbackPolicies': 'Policies',
  'chrome.fallbackAbout': 'About',
  'chrome.fallbackPrivacy': 'Privacy policy',
  'chrome.fallbackRefund': 'Refund policy',
  'chrome.fallbackShipping': 'Shipping policy',
  'chrome.fallbackTerms': 'Terms of service',

  'cart.metaTitle': 'Cart',
  'cart.pageAria': 'Cart',
  'cart.drawerAria': 'Cart drawer',
  'cart.lineItems': 'Line items',
  'cart.emptyPrompt': 'Looks like you haven’t added anything yet.',
  'cart.totals': 'Totals',
  'cart.subtotal': 'Subtotal',
  'cart.discounts': 'Discounts',
  'cart.removeDiscount': 'Remove discount',
  'cart.discountCode': 'Discount code',
  'cart.applyDiscount': 'Apply discount code',
  'cart.apply': 'Apply',
  'cart.giftCards': 'Gift cards',
  'cart.appliedGiftCards': 'Applied gift card(s)',
  'cart.giftCardCode': 'Gift card code',
  'cart.applyGiftCard': 'Apply gift card',
  'cart.quantity': 'Quantity',
  'cart.qtyDecrease': 'Decrease quantity',
  'cart.qtyIncrease': 'Increase quantity',
  'cart.continueCheckout': 'Continue to checkout',
  'cart.lineItemWith': 'Line item with {title}',

  'qty.decrease': 'Decrease',
  'qty.increase': 'Increase',
  'tag.remove': 'Remove',

  'demo.badge': 'DEMO DATA',
  'demo.badgeTitle': 'Mock data from the integration seam',

  'orderStatus.draft': 'Draft',
  'orderStatus.quote': 'Quote',
  'orderStatus.pending': 'Pending',
  'orderStatus.confirmed': 'Confirmed',
  'orderStatus.processing': 'Processing',
  'orderStatus.shipped': 'Shipped',
  'orderStatus.delivered': 'Delivered',
  'orderStatus.invoiced': 'Invoiced',
  'orderStatus.paid': 'Paid',
  'orderStatus.overdue': 'Overdue',
  'orderStatus.cancelled': 'Cancelled',
  'orderStatus.returned': 'Returned',

  'account.sidebarTitle': 'My account',
  'account.toStore': 'Back to store',
  'account.logout': 'Sign out',
  'account.orgMeta': 'Org. {orgnr} · {priceList}',
  'account.nav.ordering': 'Ordering',
  'account.nav.overview': 'Overview',
  'account.nav.quickOrder': 'Quick order',
  'account.nav.lists': 'My lists',
  'account.nav.ordersQuotes': 'Orders & quotes',
  'account.nav.orders': 'Orders',
  'account.nav.quotes': 'Quotes',
  'account.nav.company': 'Company',
  'account.nav.priceList': 'Price list',
  'account.nav.credit': 'Credit',
  'account.nav.users': 'Users',
  'account.nav.notifications': 'Notifications',
  'account.meta.suffix': 'My account',
  'account.notFound': 'Not found',

  'account.dash.greeting': 'Good morning, {name}',
  'account.dash.welcome': 'Welcome back',
  'account.dash.newOrder': 'New order',
  'account.dash.recentOrders': 'Recent orders',
  'account.dash.allOrders': 'All orders',
  'account.dash.openOrders': 'Open orders',
  'account.dash.credit': 'Credit',
  'account.dash.priceList': 'Price list',
  'account.dash.colOrder': 'Order',
  'account.dash.colDate': 'Date',
  'account.dash.colStatus': 'Status',
  'account.dash.colTotal': 'Total',

  'account.action.download': 'Download',
  'account.action.reorder': 'Reorder',
  'account.action.view': 'View',
  'account.action.track': 'Track',
  'account.action.save': 'Save',
  'account.action.create': 'Create',
  'account.action.delete': 'Delete',
  'account.action.update': 'Update',
  'account.action.updating': 'Updating…',
  'account.empty.orders': 'No orders yet.',
  'account.empty.quotes': 'No quotes yet.',
  'account.empty.lists': 'No lists yet.',
  'account.empty.addresses': 'No addresses yet.',

  'account.orders.title': 'Orders',
  'account.orders.meta': 'Orders — My account',
  'account.quotes.title': 'Quotes',
  'account.quotes.meta': 'Quotes — My account',
  'account.lists.title': 'My lists',
  'account.lists.meta': 'Lists — My account',
  'account.quickOrder.title': 'Quick order',
  'account.quickOrder.meta': 'Quick order — My account',
  'account.priceList.title': 'Price list',
  'account.priceList.meta': 'Price list — My account',
  'account.credit.title': 'Credit',
  'account.credit.meta': 'Credit — My account',
  'account.users.title': 'Users',
  'account.users.meta': 'Users — My account',
  'account.notifications.title': 'Notifications',
  'account.notifications.meta': 'Notifications — My account',
  'account.profile.title': 'My profile',
  'account.profile.meta': 'Profile — My account',
  'account.addresses.title': 'Addresses',
  'account.addresses.meta': 'Addresses — My account',
  'account.overview.meta': 'Overview — My account',

  'account.profile.firstName': 'First name',
  'account.profile.lastName': 'Last name',
  'account.profile.email': 'Email',
  'account.profile.phone': 'Phone',
  'account.addresses.add': 'New address',
  'account.addresses.edit': 'Edit address',
  'account.addresses.default': 'Set as default address',
  'account.addresses.company': 'Company',
  'account.addresses.address1': 'Address',
  'account.addresses.address2': 'Address line 2',
  'account.addresses.city': 'City',
  'account.addresses.zip': 'Postal code',
  'account.addresses.province': 'Province',
  'account.addresses.country': 'Country',

  'checkout.metaTitle': 'Checkout — {merchant}',
  'checkout.title': 'Checkout',
  'checkout.successTitle': 'Order received',
  'checkout.successBody': 'Thank you. Your order has been registered.',
  'checkout.pay': 'Pay',
  'checkout.summary': 'Summary',
  'checkout.empty': 'Your cart is empty.',
  'checkout.requestQuote': 'Submit as quote request',

  'account.users.subtitle':
    'Team members, roles, and orders waiting for approval',
  'account.users.invite': 'Invite user',
  'account.users.reject': 'Reject',
  'account.users.approve': 'Approve',
  'account.users.members': 'Team members',
  'account.users.role': 'Role',
  'account.users.orderLimit': 'Order limit',
  'account.users.unlimited': 'Unlimited',
  'account.users.active': 'Active',
  'account.users.invited': 'Invited',
  'account.users.edit': 'Edit',
  'account.quickOrder.subtitle':
    'Type or paste SKU and quantity — add the whole cart at once',
  'account.quickOrder.sku': 'SKU',
  'account.quickOrder.product': 'Product',
  'account.quickOrder.unknownSku': 'Unknown SKU',
  'account.quickOrder.validLines': 'Valid lines',
  'account.quickOrder.paste': 'Paste from spreadsheet',
  'account.quickOrder.pasteHint': 'SKU  quantity',
  'account.credit.limit': 'Credit limit',
  'account.credit.used': 'Used',
  'account.credit.available': 'Available',
  'account.credit.invoices': 'Invoices',
  'account.credit.invoice': 'Invoice',
  'account.credit.due': 'Due',
  'account.notifications.subtitle':
    'Account events and products you follow',
  'account.notifications.markAll': 'Mark all as read',
  'account.notifications.recent': 'Recent',
  'account.notifications.watchingStock': 'Watching stock',
  'account.notifications.unfollow': 'Unfollow',
  'account.lists.subtitle':
    'Saved shopping lists and scheduled recurring orders',
  'account.lists.new': 'New list',
  'account.lists.product': 'Product',
  'account.lists.sku': 'SKU',
  'account.lists.changePlan': 'Change schedule',
  'account.quotes.subtitle': 'Requests and active quotes',
  'account.quotes.validUntil': 'Valid until',
  'account.quotes.lineItems': 'Line items',
  'account.quotes.listPrice': 'List price',
  'account.quotes.offerPrice': 'Quote price',
  'account.quotes.youSave': 'You save',
  'account.priceList.product': 'Product',
  'account.priceList.sku': 'SKU',
  'account.priceList.listPrice': 'List price',
  'account.priceList.yourPrice': 'Your price',
  'account.priceList.discount': 'Discount',
  'account.orders.export': 'Export',
  'account.orders.reference': 'Reference',
  'account.orders.lineItems': 'Line items',
  'account.orders.product': 'Product',
  'account.orders.sku': 'SKU',
  'account.orders.shipping': 'Shipping',
  'account.dash.mostOrdered': 'Most ordered',
  'checkout.orderInfo': 'Order details',
  'checkout.poPlaceholder': 'e.g. PO-2026-0345',
  'checkout.notePlaceholder': 'Optional note for the warehouse',
  'checkout.shippingAddress': 'Shipping address',
  'checkout.default': 'Default',
  'checkout.invoice': 'Invoice',
  'checkout.invoiceTerms': 'Net 30 · your agreed credit limit',
  'checkout.card': 'Card',
  'checkout.cardHint': 'Pay now with company card',
  'checkout.shipping': 'Shipping',
};

const catalogs: Record<LocaleCode, Messages> = {
  'nb-NO': nb,
  en,
};

export type CopyKey = keyof typeof nb;

export type CopyVars = Record<string, string | number>;

function resolveLocale(locale?: string | null): LocaleCode {
  if (locale?.toLowerCase().startsWith('en')) return 'en';
  return 'nb-NO';
}

function interpolate(template: string, vars?: CopyVars): string {
  if (!vars) return template;
  return template.replace(/\{(\w+)\}/g, (_, key: string) =>
    vars[key] != null ? String(vars[key]) : `{${key}}`,
  );
}

/** Resolve a UI string for the active merchant locale (nb-NO default). */
export function t(
  key: CopyKey | string,
  vars?: CopyVars,
  locale = merchantConfig.locale,
): string {
  const code = resolveLocale(locale);
  const catalog = catalogs[code];
  const fallback = catalogs['nb-NO'];
  const template = catalog[key] ?? fallback[key] ?? key;
  return interpolate(template, vars);
}

/** Active UI locale derived from merchantConfig. */
export function copyLocale(): LocaleCode {
  return resolveLocale(merchantConfig.locale);
}
